### ISSUE TITLE
Recipe Book Broken

### ISSUE THREAD

**Issue by Eclipsion13** [Estecka/mc-invarpaint-crafting#1]
when this mod is installed, the vanilla recipe book is completely broken, and does not show any recipes

i'm sure this has to do with the random nature of the recipes, and so i understand if this is unfixable

as an alternative, maybe would you consider another recipe mod that does not feature randomized recipes? maybe the recipes could be related to the colors of the vanilla painting textures!

if you are already aware of this, i apologize.

i love your invariable paintings mod & will continue to use it, and most likely i will still use this mod, but this is a little annoying as i do use the recipe book quite often normally

also sorry for writing this weird i don't report bugs often

**Comment by Estecka** [comment]
That's definitely not normal, that didn't happen before the port to 1.20.5

I doubt this has to do with the random nature of recipes. In order to keep the mod server-side, I try to prevent the special recipes from being synched with the client, I'm probably blocking them all by accident. If all else fail, I can just remove that barrier, at the cost of making the mod required on clients. Although even if I did synch the painting recipe, the client wouldn't be able to display it in the recipe book.

Generating recipes based on colour is something I considered, but would be too difficult to achieve.   
If the recipes were automatically generated, similar looking paintings (e,g. Creebet and Seaside in vanilla), could easily be reduced to the same dyes and create conflicts. That would also require the logical server to be given access to the painting's textures, which it doesn't naturally have.
If the recipes were picked by hand, that would exclude all modded paintings from being crafted until additional datapacks are created specifically for those.

**Comment by Estecka** [comment]
Fixed in 1.0.1

**Comment by Estecka** [comment]
To expand a bit on the idea of hand-picked recipes: it's something that someone should be able to do without the help of any mod. A simple datapack would suffice, since 1.20.5 allows shaped recipes to attach data-components to their output. With this method, the different recipes for each paintings would also appear in the recipe book.
